export const ALL_CONTENT_REQUEST = "ALL_CONTENT_REQUEST";
export const ALL_CONTENT_SUCCESS = "ALL_CONTENT_SUCCESS";
export const ALL_CONTENT_FAIL = "ALL_CONTENT_FAIL";
export const CONTENT_DETAILS_REQUEST = "CONTENT_DETAILS_REQUEST";
export const CONTENT_DETAILS_SUCCESS = "CONTENT_DETAILS_SUCCESS";
export const CONTENT_DETAILS_FAIL = "CONTENT_DETAILS_FAIL";
export const CLEAR_ERROR = "CLEAR_ERROR"