export const ALL_CONTENT_REQUEST = "ALL_CONTENT_REQUEST";
export const ALL_CONTENT_SUCCESS = "ALL_CONTENT_SUCCESS";
export const ALL_CONTENT_FAIL = "ALL_CONTENT_FAIL";
export const CLEAR_ERROR = "CLEAR_ERROR"